repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: check-docstring-first

  # Use bin/check for all formatting, linting, and type checking
  # This prevents tool conflicts and ensures consistency

  - repo: local
    hooks:
      - id: quality-check
        name: quality-check (formatting, linting, type checking)
        entry: bin/check
        language: system
        pass_filenames: false
        files: '^.+\.py$'
        args: [--fix]
      - id: pytest-check
        name: pytest-check
        entry: bin/test
        language: system
        pass_filenames: false
        files: '^.+\.py$'
        args: [--unit]

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
